title: PSEUDO
description: Computational framework for debiasing and uncertainty quantification in protein structural models resolved by molecular replacement.

theme: just-the-docs

aux_links:
  "GitHub":
    - "https://github.com/hamlet-khachatryan/PSEUDO"

footer_content: "Copyright &copy; 2026 Hamlet Khachatryan, Conor Wild, Frank von Delft."

highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - theory.md